version: '3'

services:
  node:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
      - /app/node_modules
    depends_on:
      - mysqldb
    environment:
     - DATABASE_HOST=mysqldb
     - NODE_ENV=development
    links:
      - mysqldb

  mysqldb:
    build: ./service_database
    restart: always
    ports:
      - '3307:3306'
